      PROGRAM QUAF_S
C     FUER SMIN STATTDESSEN
CC    SUBROUTINE QUAF
      IMPLICIT REAL*8 (A-H,O-Z)
C
C     FUER ARGONNE-18 POTENTIAL
C     VERSION FUER 6 CLUSTER
C     VERLANGT KURZOBFILES!!!!!!!!!!!!!!!!
C     FUER SMIN VORBEREITET
C     JEWEILS 'SMIN' SUCHEN UND DIE ENTSPRECHENDEN AENDERUNGEN DURCHFUEHREN
C     DIE LAENGE DES COMMON BLOCKS 'COMOV' MUSS MIT DER IN SMINH PASSEN
C     DESHALB DURCHGEHEND 'par/QUAF' durch 'par/SMIN' ANDERN
C
C     QUAF BERECHNET DIE REDUZIERTEN ORSTRAUMMATRIXELEMENTE
C     UND MULTIPLIZIERT SIE MIT DEN REDUZIERTEN SPINMATRIX-
C     ELEMENTEN
C
C     29.7.97 IN BEGRI LOOP 166 MODIFIZIERT H.M.H.
C     16.1.98 NKSU VON KOBER WIRD ZUR ZUWEISUNG DER DREHIMPULSE BEI
C             6 CLUSTERN BENUTZT H.M.H.
C     1.9.98  POTENTIAL UND ZUGEHOERIGE PARAMETER WERDEN JETZT VON EXTRA
C             FILE EINGELESEN, DAMIT NNN-WECHSELWIRKUNG EINFACHER ZU
C             HANDHABEN H.M.H.
C     3.2.99 FUER INDEKO UNGLEICH NULL WIRD NUR DER KOPF VON KOBOUT GELESEN,    
C            DIE MATRIXELEMENTE WERDEN VON EINZELNEN FILES GELESEN, DEREN       
C            NAMEN AM ENDE VON INQUA EINGELESEN WERDEN H.M.H.   
C
C     1. OPERATOR: NORM
C     2. OPERATOR: KIN. ENERGIE
C     3. OPERATOR: COULOMB
C     4. OPERATOR: ZENTRAL
C     5. OPERATOR: P-QUADRAT
C     6. OPERATOR: R-QUADRAT
C     7. OPERATOR: SPIN-BAHN
C     8. OPERATOR: TENSOR
C     9. OPERATOR: TENSOR_p antisymmetric
C
C     INPUT DES PROGRAMMS
C      INTEGERS IM FORMAT 24I3, REALS IM FORMAT 6E12.4
C
C      BEZEICHNUNG DER BAENDER
C      FILENAME FUER POTENTIAL,UNIT=25
C     von unit=25: DIE STEUERKARTE FUER DIE ZU RECHNENDEN OPERATOREN
C     von unit=25: DIE STEUERKARTEN FUER DIE KORRELATIONSFUNKTIONEN
C     von unit=25: DIE DEFINITION DER POTENTIALE
C
C EINGABE FUER DIE FUNKTIONEN
C
C JEDER INDEX I) ENTSPRICHT EINER KARTE
C
C DER FOLGENDE DATENSATZ MUSS FUER JEDE FUNKTION (K=1,NZF) WIEDERHOLT
C WERDEN
C  A) ZAHL DER PARAMETERSAETZE                                     NZPAR
C     DIE INNEREN WEITEPARAMETER
C     DIE RADIALWEITEPARAMETER
C WENN NBAND5=0,WIRD ALLES NEU GERECHNET,WENN NBAND5#0,WIRD VON DIESEM B
C  TEIL UBERNOMMEN
C
C
      INCLUDE 'par/QUAF_EFT'
C     NZOPER: ANZAHL DER OPERATOREN IN QUAF
C     NZOPOB:   "     "      "      "  OBER
C     NZOPLU:   "     "      "      "  LUDWIG
C     NZTMAX: MAXIMALE ANZAHL DER TEILCHEN
C     NZFMAX:     "      "     "  ZERLEGUNGEN
C     NZCMAX:     "      "     "  CLUSTER
C     MZGMAX:     "      "     "  SPINFUNKTIONEN
C     NZLWMA:     "      "     "  DREHIMPULSSTRUKTUREN
C     NZRHOM:     "      "     "  BASISVEKTOREN PRO ZERLEGUNG
C     NZPARM:     "      "     "  SAETZTE INNERER WEITEN
C     MZPARM:     "      "     "  RADIALPARAMETER
C     NZPOMA:     "      "     "  POLYNOMSTRUKTUREN
C     NZIQMA:     "      "     "  SIGMAFAKTOREN AUS LUDWIG
C     NZPOTM:     "      "     "  POTENTIALE
C     NZSIOP:     "      "     "  SPIN-ISOSPIN OPERATOREN
C     NPDC:       "      "     "  PDC'S AUS OBER
C
      PARAMETER (NZAVMA=2*NZCMAX-1, NZVMAX=NZTMAX-1,
     *           NZMAT=MZGMAX*MZGMAX*NZSIOP,
     *           NDIM4=NZPOMA*NZLWMA, NZLRH=(2*NZCMAX-3)*(NZCMAX-1),
     *   NZLREC=2*NZCMAX  + NZLRH+(NZLRH*(NZLRH+1))/2)
C
      COMMON /LUP/ KVK(NDIM1), JQ(NDIM1), INDPO(NDIM1),
     *    MVK(NDIM1,NZIQMA), EPO(NDIM1), WERTL(NDIM4,NDIM4),
     *    IZ,JZ, KZHV(2,NZLREC+1), LUPAUS, IQM(NZLREC+1),
     *    KZHX(0:NZIQMA,NZLREC+1)
C
      COMMON /SC/ ABC(4), ABD(4), ABE(4), KORR, NZT
C
      COMMON /LUR/ IENT(NZOPLU), NBAND3
C
      COMMON /BIG/ DM(NDIM,NDIM,2)
C
      COMMON /BEG/ POWE, IZLURE, INQ(NZOPER), NAUS
C
      COMMON /CSH/ NSH1(NDIM5), NSH2(NDIM5), SH(NDIM5), NSH
C
      COMMON /COMOV/ NOVQ(NZFMAX), MOVQ(NZFMAX),
     *               COV(2*NZCMAX-2,NZPARM,NZFMAX),
     *               ROV(MZPARM,NZFMAX)
C
      COMMON  MKC, NZV, QO(NZVMAX,NZVMAX), QOR(NZVMAX,NZVMAX),
     *        VZ(NZVMAX,NZVMAX), WERT(NDIM4,NDIM4), UR(NZVMAX),
     *        LPARR, MC1, MD1, MFL, NCC, NREB, NZAV, NZV1, PHI2,
     *        RPAR(MZPARM,NZFMAX), VR(NZTMAX,NZCMAX-1),
     *        WR(NZTMAX)
C
      COMMON /STOREQ/ COF(NZPARM,NZRHOM,NZFMAX), RVEC(NZVMAX,NZTMAX),
     *          SVEC(NZTMAX,NZVMAX), U(MZGMAX,MZGMAX,NZSIOP,NPDC),
     *          UU(MZGMAX,MZGMAX), VW(NZTMAX,NZCMAX-1),
     *          NUM(5,NZRHOM,NZFMAX), NREG(NZOPOB)
      DIMENSION WECPOT(NZPOTM,6,NZOPER)
      DIMENSION NZC(NZFMAX), MZG(NZFMAX), NOL(NZFMAX),
     *          NGRV(2,NZCMAX,NZFMAX), NKCM(NZOPER),
     *          NZPAR(NZFMAX), NZPOT(NZOPER)
      DIMENSION MS(MZGMAX,NZFMAX), MZPAR(NZFMAX),
     *          POLL(NZVMAX,NZVMAX), PORR(NZVMAX,NZVMAX),
     *          CPAR(NZAVMA-1,NZPARM,NZFMAX)
      DIMENSION QFCL(NZVMAX,NZVMAX,2*NZCMAX-1), LC(NZTMAX,NPDC),
     *          QFCR(NZVMAX,NZVMAX,2*NZCMAX-1), LC1(NZTMAX),
     *          QFO(NZVMAX,NZVMAX), POR(NZVMAX,NZVMAX),
     *          POL(NZVMAX,NZVMAX), NOP(NZOPER)
      DIMENSION LREG(NZOPER), KOM(NZOPER,NZFMAX,NZFMAX)
      DIMENSION MMASSE(2,MZGMAX,NZFMAX), MLAD(2,MZGMAX,NZFMAX),
     *          MSS(2,MZGMAX,NZFMAX),IVEK1(NZFMAX)
      DIMENSION NZLW(NZFMAX), LW(2*NZCMAX-1,NZLWMA,NZFMAX),
     *          LZWERT(5,NZLWMA,NZFMAX), NZRHO(NZFMAX),
     *          NZC1(NZFMAX), IVEK(NZFMAX), K1VEC(NZFMAX),
     *          NZPO(NZFMAX), KP(NZCMAX-1,NZPOMA,NZFMAX)
      DIMENSION LREG1(NZOPER), NZRHO1(NZFMAX), ITPO(NZFMAX),
     *          NT1(NPDC), NT2(NPDC), JREOB(NZOPER), JRELU(NZOPER),
     *          WERTNO(NDIM4,NDIM4), WERTTE(NDIM4,NDIM4)
      DIMENSION IMV(NZMAT), UM(NZMAT), LCALT(NZTMAX), NKSU(NZFMAX)
C
      CHARACTER*80 INFILO, INFILU
      CHARACTER*50 VARFOR(NZOPER)
      CHARACTER*80 CPOTFIL
C
      DATA VARFOR/'('' NORM'')','('' KINETISCHE ENERGIE'')',
     *'('' COULOMB'')','('' ZENTRAL '')',
     *'('' P-QUADRAT-POTENTIAL'')','('' R-QUADRAT-POTENTIAL'')',
     *'(''  SPIN-BAHN'')','('' TENSOR'')',
     *'('' TENSOR_p antisymmetrisch'')'/
C
      DATA NZPOT/NZOPER*1/
C
      DATA NKCM/1,1,1,4,4,4,2,2,2/
      DATA JRELU/1,2,3,0,0,4,5,6,7/
      DATA JREOB/1,0,2,3,0,0,4,5,0/
C
C     FUER SMIN SIND DIE MIT 'CC' VERSEHENEN KARTEN ZU AKTIVIEREN UND
C     DIE ANGEGEBENEN ZEILEN ZU DEAKTIVIEREN
C
      OPEN(UNIT=5 ,FILE='INQUA_N'  ,STATUS='OLD')
      OPEN(UNIT=9 ,FILE='LUCOUT',STATUS='OLD',FORM='UNFORMATTED')
      OPEN(UNIT=10,FILE='QUAOUT',STATUS='UNKNOWN',FORM='UNFORMATTED')
C
      OPEN(UNIT=6 ,FILE='OUTPUT')
      OPEN(UNIT=8 ,FILE='KOBOUT', STATUS='OLD',FORM='UNFORMATTED')
C     IN SMIN MUESSEN DIESE OPEN STATEMENTS UNWIRKSAM GEMACHT WERDEN
      WRITE(NOUT, 1111)
1111  FORMAT('1 QUAFL_EFT_new VERSION VOM 11.09.2007')
      INPUT=5
      INPOT=25
      PHI=3.1415926535897932384D0
      PHI2=  SQRT(PHI)
      E2=0.51098*2.81785*2.0/PHI**0.5
      WRITE (NOUT,1000)
      DO 1   K=1,NZPOTM
      DO 1 L=1,NZOPER
      DO 2  M=1,3,2
    2 WECPOT(K,M,L)=1.
    1 WECPOT(K,2,L)=0.
      READ (INPUT,1002) NBAND1,NBAND2,NBAND3,IDUM,NBAND5,NAUS,MOBAUS
     1 ,LUPAUS, ISTOP
      IF(NBAND5.EQ.12) OPEN(UNIT=12,FILE='QUAALT',STATUS='UNKNOWN',
     *                 FORM='UNFORMATTED')
      READ(INPUT,993) CPOTFIL
993   FORMAT(A80)
      OPEN(UNIT=25,FILE=CPOTFIL,STATUS='OLD',FORM='FORMATTED')
      READ(INPOT,1002)(LREG(K),K=1, NZOPER)
C --- changed from 6e12.4 to 6e20.7 for larger potential strength parameters in EFT
 1020 FORMAT(6E20.13)
C     KORRELATIONSFUNKTION
      A=0.
      B=1.
      READ (INPOT,1002) NKOR,(NOP(K),K=1,NZOPER)
      WRITE(NOUT,1022)
      IF(NKOR-1) 200,201,7201
201   CONTINUE
C     B (ABFALLPARAMETER) WIRD STETS POS.EINGELESEN
      READ(INPOT,1020) A,B
      WRITE (NOUT,1023)A,B
  200 CONTINUE
      WRITE (NOUT,1024)
      WRITE(NOUT,1025) (NOP(K),K=1,NZOPER)
 1022 FORMAT(///26H KORRELATIONSFUNKTION = 1./)
1023  FORMAT(24X,F9.5,7H *EXP(-,F8.4,7H *R**2),/)
 1024 FORMAT(2X,11H R IN FERMI,//)
 1025 FORMAT(/,' BEIM OPERATOR  1  2  3  4  5  6  7  8  9 10 11 12 ',
     1'13 14 WIRD DIE KORELATIONSFUNKTION AUS',/,14X,14I3,
     2'  GAUSSFUNKTIONEN GEBILDET',/)
      ABC(1)=1.
      ABE(1)=.0
      ABD(1)=0.
      ABC(2)=A
      ABD(2)=B
      ABE(2)=.0
      ABC(3)=A
      ABD(3)=.0
      ABE(3)=B
      ABD(4)=B
      ABC(4)=A   *A
      ABE(4)=B
C      ENDE KORRELATIONFUNKTION
C     POTENTIAL EINLESEN
      READ (INPOT,1002)  (NZPOT(K), K=4,NZOPER)
      DO 530 K=4,NZOPER
      IF(NZPOT(K).EQ.0) LREG(K) = 0
  530 CONTINUE
      WECPOT(1,1,3)=WECPOT(1,1,3)*E2
      DO 742 MKC=4,NZOPER
      IF(NZPOT(MKC).EQ.0) GOTO 742
      DO 741 K=1,NZPOT(MKC)
741   READ(INPOT,1020)(WECPOT(K,M,MKC),M=1,NKCM(MKC)+2)
742   CONTINUE
1042  FORMAT(' ANZAHL DER POTENTIALE',I4)
1044  FORMAT(//)
1043  FORMAT(' VORFAKTOR=',G20.7,' BETA',F11.5,
     1   ' W  =',G20.7,' M  =',G20.7,' B  =',G20.7,' H  =',G20.7)
C     POTENTIAL EINLESEN
      DO 757 MKC=4,NZOPER
      IF(NZPOT(MKC).EQ.0) GOTO 757
      WRITE(NOUT,1044)
      WRITE(NOUT,VARFOR(MKC))
      WRITE(NOUT,1042) NZPOT(MKC)
      WRITE(NOUT,1043)((WECPOT(I,M,MKC),M=1,6),I=1,NZPOT(MKC))
757   CONTINUE
C     EINLESEN DER FUNKTIONSEIGENSCHAFTEN UND PARAMETER
      REWIND  NBAND2
      READ(NBAND2) NZF,NZT,(NREG(K),K=1,NZOPOB),INDEKO   
      IF(INDEKO.NE.0) WRITE(NOUT,*)' OBERMATRIXELEMENTE VON EINZELFILES'
      NZV=NZT-1
      IF(MOBAUS.GT.0) WRITE(NOUT,*)'NZF,NZT,(NREG(K),K=1,NZOPOB),INDEK',
     *                NZF,NZT,(NREG(K),K=1,NZOPOB),INDEKO
      IF(NBAND5.LE.0) GOTO 90
      DO 92 KL=1,NZF
      DO 92 KR=1,KL
   92 READ(INPUT,1002) (KOM(L,KL,KR),L=1,NZOPER)
      REWIND NBAND5
      GO TO 93
   90 CONTINUE
      WRITE(NOUT,6100)
      DO 94 KL=1,NZF
      DO 94 KR=1,KL
      DO 94 L=1,NZOPER
   94 KOM(L,KL,KR)=0
   93 CONTINUE
      NZV1 = NZV - 1
      WECPOT(1,1,1)=2./ DBLE(NZT*NZV)
      DO 20  K = 1,NZF
      READ (NBAND2) NZC(K),MZG(K),NOL(K)
      IF(MOBAUS.GT.0) WRITE(NOUT,*)' NZC(K),MZG(K),NOL(K)',
     *                NZC(K),MZG(K),NOL(K)
      M = MZG(K)
      IF(M.LE.MZGMAX) GOTO 6002
      WRITE(NOUT,*) 'ZERLEGUNG,MZG,MZGMAX',K,MZG(K),MZGMAX
      GO TO 250
6002  NOL(K)=NOL(K)+1
      READ (NBAND2) ((MMASSE(N,L,K),MLAD(N,L,K),MSS(N,L,K),N=1,2),
     1     MS(L,K),L=1, M)
      IF(MOBAUS.GT.0) WRITE(NOUT,*) 'MMASSE,MLAD,MSS,MS',
     * ((MMASSE(N,L,K),MLAD(N,L,K),MSS(N,L,K),N=1,2),MS(L,K),L=1, M)
      M = NZC(K)
      READ (NBAND2) ((NGRV(N,L,K),L=1,M),N=1,2),NKSU(K)
      IF(MOBAUS.GT.0) WRITE(NOUT,*)'NGRV',((NGRV(N,L,K),L=1,M),N=1,2),
     *              ' NKSU ',NKSU(K)
   20 CONTINUE
C
      REWIND NBAND3
      READ(NBAND3) NZF1,(NZLW(K),NZC1(K),K=1,NZF1),(IENT(K),K=1,NZOPLU),
     1  (NZPO(MH),MH=1,NZF1),INDELU
      IF(INDELU.NE.0) WRITE(NOUT,*)' LUDWMATRIXELEMENTE VON EINZELFILES'
      IF(NAUS.GT.0) WRITE(NOUT,248) NZF1,IENT,(NZLW(K),NZC1(K),NZPO(K),
     1  K=1,NZF1)
248    FORMAT(' VON LUPO,ZAHL DER ZERLEGUNGEN',I4,' OPERATOREN',7I4,/,
     1  (' ZAHL DER DREHIMPULSE',I4,' ZAHL DER CLUSTER',I4,
     2  'ZAHL DER POLYNOME',I4,/))
      IF(NZF.LE.NZF1) GOTO 251
      STOP 251
  250 STOP 250
  251 DO 252 K=1,NZF
      ITPO(K)=0
      IF(NZPO(K).NE.0) ITPO(K)=2
      NZPO(K)=MAX0(1,NZPO(K))
      IF(NZC(K).NE.NZC1(K)) THEN
        write(nout,*)'K: NZC(K) <> NZC1(K)',K, NZC(K),NZC1(K)
        STOP 252
      ENDIF
  252 CONTINUE
C
C     UEBERPRUEFUNG, OB GERECHNETE OPERATOREN IN OBER, LUDWIG UND
C     QUAF ZUSAMMENPASSEN
C
C     CHECK FUER NORM
      IF (IENT(1).EQ.0) STOP 253
      IF (LREG(2).EQ.0) GOTO 254
C     CHECK FUER KINETISCHE ENERGIE
      IF (IENT(2).EQ.0) STOP  254
254   IF (LREG(3).EQ.0) GOTO 256
C     CHECK FUER COULOMB
      IF (IENT(3).EQ.0 .OR. NREG(2).EQ.0) STOP  256
256   IF (LREG(4).EQ.0) GOTO 258
C     CHECK FUER ZENTRAL
      IF (NREG(3).EQ.0) STOP  258
258   IF (LREG(5).EQ.0) GOTO 260
C     CHECK FUER P**2 POTENTIAL
      IF (NREG(3).EQ.0) STOP  260
260   IF (LREG(6).EQ.0) GOTO 1261
C     CHECK FUER R**2 POTENTIAL
      IF (NREG(3).EQ.0 .OR. IENT(4).EQ.0) STOP 1261
1261  IF (LREG(7).EQ.0) GOTO 1256
C     CHECK FUER LS POTENTIAL
      IF (NREG(4).EQ.0 .OR. IENT(5).EQ.0) STOP 1256
1256  IF (LREG(8).EQ.0) GOTO 1262
C     CHECK FUER TENSOR POTENTIAL
      IF (NREG(5).EQ.0 .OR. IENT(6).EQ.0) STOP  1256
1262  IF (LREG(9).EQ.0) GOTO 262
C     CHECK FUER TENSOR_p anti POTENTIAL
      IF (NREG(5).EQ.0 .OR. IENT(7).EQ.0) STOP  1262
262   CONTINUE
C     CHECK OBER/LUDWIG ZU ENDE
C
C     KONSTRUKTION DER BAHNDREHIMPULSE
      DO 264 K=1,NZF
      M1=2*NZC(K)-3
      M2=NZLW(K)
      IF(M2.LE.NZLWMA) GOTO 6000
      WRITE(NOUT,*) 'ZERLEGUNG,NZLW,NZLWMA',K,NZLW(K),NZLWMA
      GO TO 250
 6000 CONTINUE
      M3=NZC(K)-1
      MPO=NZPO(K)
      READ(NBAND3) ((LW(M,L,K),M=1,M1),L=1,M2),((KP(M,KH,K),M=1,M3),
     1 KH=1,MPO)
      IF(LUPAUS.LT.1) GOTO 263
      DO 1333 L=1,M2
1333  WRITE (NOUT,1334) (LW(M,L,K),M=1,M1),NOL(K)
1334  FORMAT(' LWERT, NOL',10I5)
263   CONTINUE
      DO 265 L=1,M2
      DO 266 M=1,3
  266 LZWERT(M,L,K)=0
      LZWERT(4,L,K)=LW(M3,L,K)
      LZWERT(5,L,K)=LW(M1,L,K)
      GOTO(261,265,267,268,276,282,261), NZC(K)
261   STOP 'NZC'
C     3-CLUSTER
  267 LZWERT(3,L,K)=LW(1,L,K)
      IF(NOL(K).EQ.NZC(K)) LZWERT(1,L,K)=LW(1,L,K)
      IF(NOL(K).EQ.2) LZWERT(2,L,K)=LW(1,L,K)
      GO TO 265
C     4-CLUSTER
  268 LZWERT(3,L,K)=LW(4,L,K)
      IF(NOL(K).LT.NZC(K)) GOTO 272
      LZWERT(1,L,K)=LZWERT(3,L,K)
      GO TO 265
  272 IF(NOL(K).GT.2) GOTO 275
      LZWERT(2,L,K)=LZWERT(3,L,K)
      GO TO 265
  275 LZWERT(1,L,K)=LW(1,L,K)
      LZWERT(2,L,K)=LW(2,L,K)
      GOTO 265
C     5-CLUSTER
276   LZWERT(3,L,K)=LW(6,L,K)
      GOTO (277,278,279,280,281,277),NOL(K)
277   STOP 'NOL'
278   LZWERT(2,L,K)=LW(6,L,K)
      GOTO 265
279   LZWERT(1,L,K)=LW(1,L,K)
      LZWERT(2,L,K)=LW(5,L,K)
      GOTO 265
280   LZWERT(1,L,K)=LW(5,L,K)
      LZWERT(2,L,K)=LW(3,L,K)
      GOTO 265
281   LZWERT(1,L,K)=LW(6,L,K)
      GOTO 265
C     6-CLUSTER
282   LZWERT(3,L,K)=LW(8,L,K)
      GOTO (277,283,284,285,286,287,277),NOL(K)
283   LZWERT(2,L,K)=LW(8,L,K)
      GOTO 265
284   LZWERT(1,L,K)=LW(1,L,K)
      LZWERT(2,L,K)=LW(7,L,K)
C     HIER PASST ZUFAELLIGERWEISE DIE REIHENFOLGE DER KOORDINATEN MIT DER
C     DER DREHIMPULSE UEBEREIN
      GOTO 265
285   LZWERT(1,L,K)=LW(6,L,K)
      LZWERT(2,L,K)=LW(7,L,K)
      GOTO 265
286   LZWERT(1,L,K)=LW(7,L,K)
      LZWERT(2,L,K)=LW(NZC(K)-NKSU(K),L,K)
      GOTO 265
287   LZWERT(1,L,K)=LW(8,L,K)
  265 CONTINUE
  264 CONTINUE
C      BAHNDREHIMPULSE ENDE
C      KONSTRUKTION DER BASISVEKTOREN
      I=0
      WRITE (NOUT,1000)
 1000 FORMAT(1H1)
      DO 22  K = 1,NZF
      NZPAR(K) = 0
      MZPAR(K) = 0
       READ(INPUT,1002) NZRHO(K)
      KK=NZRHO(K)
      IF(KK.LE.NZRHOM) GOTO 388
      WRITE(NOUT,*) 'ZERLEGUNG,NZRHO,NZRHOM',K,NZRHO(K),NZRHOM
      GOTO 250
388   IVEK(K)=I
      IF(KK.EQ.0) GOTO 22
      M = 2*NZC(K) - 2
      WRITE (NOUT,1001)  K
 1001 FORMAT(//25H WEITEPARAMETER FUER DIE ,  I3,
     1       47H TE CLUSTERSTRUKTUR IN REZIPROKEN FERMIQUADRAT     )
      READ (INPUT,1002)  NZPAR(K) ,MZPAR(K)
CC    NZPAR(K)=NOVQ(K)
CC    MZPAR(K)=MOVQ(K)
C     DIESE KOMMENTARE SIND IN SMIN ZU AKTIVIEREN UND DAS VORANGEHENDE READ
C     UNWIRKSAM ZU MACHEN
 1002 FORMAT(20I3)
      IF(MZPAR(K).GT.MZPARM) STOP 'MZPARM ZU KLEIN'
      LM = NZPAR(K)
      KM=MZPAR(K)
      IF(LM.LE.NZPARM) GOTO 390
      WRITE(NOUT,*) ' ZUVIELE INTERNE PARAMETERSAETZE',NZPAR(K),NZPARM
      GOTO 250
390   DO 24  L = 1,LM
      READ (INPUT,1003)  (CPAR(N,L,K),N=1,M)
      DO 124 N=NZC(K)+1,M
      IF(CPAR(N,L,K).GT.0.)  GOTO 124
      WRITE(NOUT,*)' WEITE ',N,' FALSCH'
      STOP 'INTERNE WEITE FALSCH'
  124 CONTINUE
 1003 FORMAT(6E12.4)
   24 WRITE (NOUT,1004)L,(  CPAR(N,L,K),N=1,M)
 1004 FORMAT(/I3,' TER SATZ INNERER WEITEN',/,(8F12.6))
      READ(INPUT,1003)  (RPAR(L,K),L=1,KM)
      DO 125 L=1,KM
CC    RPAR(L,K)=ROV(L,K)
C     FUER SMIN AKTIVIEREN UND DAS READ DEAKTIVIEREN
      IF(RPAR(L,K).GT.1.E-8) GOTO 125
      WRITE(NOUT,*) ' IN ZERLEGUNG ',K,' IST DIE RELATIVWEITE ',L,
     *              ' FALSCH'
125   CONTINUE
C
      WRITE(NOUT,1005)   (RPAR(L,K),L=1,KM)
 1005 FORMAT(/22H SATZ RADIALPARAMETER   /3(8F12.6/))
      DO 240 N=1,KK
      READ(INPUT,1002) NUM(1,N,K),NUM(2,N,K),NUM(4,N,K),NUM(5,N,K)
C     NUM(5,.,.) # 0: BASISVEKTOR WIRD NICHT NEU GERECHNET
C
      NUM(4,N,K)=MAX(1,NUM(4,N,K))
      NUM(3,N,K)=IVEK(K)+N
      READ(INPUT,1003) (COF(L,N,K),L=1,LM)
      WRITE(NOUT,1050) NUM(3,N,K),K,NUM(1,N,K),NUM(2,N,K),NUM(4,N,K),
     1  (COF(L,N,K),L=1,LM)
 1050 FORMAT(//15H DEFINITION DER,I3,22H TEN BASISFUNKTION IST/
     1 I3,13H TE ZERLEGUNG,I3,23H TE SPINISOSPINFUNKTION/I3,
     2 26H TE BAHNDREHIMPULSFUNKTION,I3,' TES POLYNOM',/,
     3 ' SUMMATION UEBER INNERE WEITEN MIT KOEFFIZIENTEN',/,(1P6E12.4))
          IF(NUM(1,N,K).EQ.0 .OR. NUM(1,N,K).GT.MZG(K)) THEN
          WRITE(NOUT,*) ' DIESER BASISVEKTOR HAT FALSCHE SPINFUNKTION'
          STOP 240
          ENDIF
          IF(NUM(2,N,K).EQ.0 .OR. NUM(2,N,K).GT.NZLW(K)) THEN
          WRITE(NOUT,*) ' DIESER BASISVEKTOR HAT FALSCHE BAHNFUNKTION'
          STOP 240
          ENDIF
      IF (NUM(5,N,K).GT.0) WRITE (NOUT,1051)
  240 CONTINUE
      I=I+KK
   22 CONTINUE
C     ENDE DEFINITION BASISVEKTOREN
2011  FORMAT(////18H BERECHNET WERDEN )
      WRITE (NOUT,2011)
      DO 611 IPV=1,NZOPER
      IF(LREG(IPV).GT.0) WRITE(NOUT,VARFOR(IPV))
611   CONTINUE
      REWIND NBAND1
      IF(NBAND5.LE.0) GOTO 800
      READ(NBAND5) NZF1,(LREG1(K),K=1,NZOPER),I1,
     1 (NZRHO1(K),K=1,NZF1)
      IVEK1(1)=0
      MFEH1 = 1
      MFEH2 = NZF
      MFEH3 = NZF1
      IF(NZF.LT.NZF1) GOTO 890
      DO 804 K=1, NZOPER
      MFEH1 = 3+ K
      MFEH2 = LREG(K)
      MFEH3 = LREG1(K)
      IF(LREG(K)-LREG1(K))804,804,806
  806 DO 807 ML=1,NZF1
      DO 807 MR=ML,NZF1
  807 KOM(K,ML,MR)=0
  804 CONTINUE
      DO 805 K=1,NZF1
      MFEH1=11 + K
      MFEH2=NZRHO(K)
      MFEH3 = NZRHO1(K)
      IVEK1(K+1)=IVEK1(K)+NZRHO1(K)
  805 CONTINUE
      DO 6020 ML=1,NZF
      DO 6020 MR=1,ML
      IF(ML.LE.NZF1) GOTO 6020
      DO 6022 MC=1, NZOPER
 6022 KOM(MC,ML,MR)=0
 6020 CONTINUE
      GO TO 800
  890 WRITE(NOUT,891) MFEH1,MFEH2,MFEH3
  891 FORMAT( 17H VERGLEICHSFEHLER ,3I4)
      STOP
  800 CONTINUE
      WRITE(NBAND1) NZF,(LREG(K),K=1,NZOPER),I,(NZRHO(K),K=1,NZF)
      DO 950  K = 1,NZF
      M=MZG(K)
      N3=MZPAR(K)
      MC1=NZC(K)-1
      K1VEC(K)=N3
      KK=NZRHO(K)
      IF(KK*N3.LE.NDIM)GOTO 930
      WRITE(NOUT,*) ' NDIM FUER ZERLEGUNG ',NZF,' ZU KLEIN, MINIMAL ',
     *             KK*N3
      STOP 930
930   IF(KK.LE.0) GOTO 809
      DO 4536 N=1,KK
      N1=NUM(1,N,K)
      N2=NUM(2,N,K)
       N4=NUM(4,N,K)
      WRITE(NBAND1) N3,MMASSE(1,N1,K),MMASSE(2,N1,K),MLAD(1,N1,K),
     1 MLAD(2,N1,K),MSS(1,N1,K),MSS(2,N1,K),MS(N1,K),
     2 (LZWERT(L,N2,K),L=1,5),(RPAR(L,K),L=1,N3),KP(MC1,N4,K)
 4536 CONTINUE
809   IF(NBAND5.LE.0) GOTO810
       IF(K.GT.NZF1)GOTO 810
       KK1=NZRHO1(K)
      DO 813 N=1,KK1
813    READ(NBAND5)
810   CONTINUE
  950 CONTINUE

      WECPOT(1,1,2) = -(2.72099*0.529172*137.0373)**2/
     1                 (2.0*(938.211+939.505)* DBLE(NZT))
c      WECPOT(1,1,2) = -(2.72099*0.529172*137.0373)**2/
c     1                 ((938.211+939.505)* DBLE(NZT))     
c      WECPOT(1,1,2) = -(2.72099*0.529172*137.0373)**2/
c     1                 (2*(1226.0)* DBLE(NZT))  
c      WECPOT(1,1,2) = -(2.72099*0.529172*137.0373)**2/
c     1                 (2*(1634.0)* DBLE(NZT))  
c      WECPOT(1,1,2) = -38933.65630005578/(6572.430*DBLE(NZT))
      ISTOPP=0
C
C     IF(NBAND5.NE.0) WRITE(NOUT,*) 'IVEK1',IVEK1,'IVEK',IVEK
C     IF(NBAND5.NE.0) write(NOUT,*) 'nzrho1',nzrho1,'nzrho',nzrho
C
      IF(INDEKO.NE.0) THEN                               
      MEFOB=23                                                           
      CLOSE(UNIT=8,STATUS='KEEP')                                    
      NBAND2=MEFOB                                                  
      ENDIF       
         IF(INDELU.NE.0) THEN                               
         MEFLU=25                                                           
         CLOSE(UNIT=9,STATUS='KEEP')                                    
         NBAND3=MEFLU                                                  
         ENDIF       
C     BESTIMMUNG DER ORTSMATRIXELEMENTE VOR EINSETZEN DER DREHIMPULSE
      DO 40  MFL = 1,NZF
      IZLW=NZLW(MFL)
      IZPW=NZPO(MFL)
      IRHO=NZRHO(MFL)
      IK1=K1VEC(MFL)
      MC = NZC(MFL)
      MC1= MC - 1
      MC2 = MC + MC1
      MC3 = MC2 - 1
      NC= NZPAR(MFL)
      NCC = MZPAR(MFL)
      IF(INDEKO.EQ.0) THEN
         READ(NBAND2)   ((RVEC(M,N),M=1,NZV),N=1,NZT)
         READ(NBAND2)   ((SVEC(N,M),M=1,NZV),N=1,NZT)
         READ(NBAND2)   (((QFCL(M,N,K),M=1,NZV),N=1,NZV),K=1,MC2)
      ENDIF
      DO 40 MFR=1,MFL
      JZLW=NZLW(MFR)
       JZPW=NZPO(MFR)
      JRHO=NZRHO(MFR)
      JK1=K1VEC(MFR)
      WRITE(NOUT,3009) MFL,MFR
      NLUDZ=0
3009  FORMAT(//,19H ZWISCHEN ZERLEGUNG,I3,15H UND ZERLEGUNG ,I3,
     124H WIRD ZUR ZEIT GERECHNET )
      MD=NZC(MFR)
      MD1= MD - 1
      IF(INDEKO.NE.0) THEN
         READ(INPUT,378) INFILO
378      FORMAT(A80)
         OPEN(UNIT=MEFOB,FILE=INFILO,STATUS='OLD',FORM='UNFORMATTED')
          REWIND MEFOB 
         READ(NBAND2)   ((RVEC(M,N),M=1,NZV),N=1,NZT)
         READ(NBAND2)   ((SVEC(N,M),M=1,NZV),N=1,NZT)
         READ(NBAND2)   (((QFCL(M,N,K),M=1,NZV),N=1,NZV),K=1,MC2)
      ENDIF 
      IF(INDELU.NE.0) THEN
         READ(INPUT,378) INFILU
         OPEN(UNIT=MEFLU,FILE=INFILU,STATUS='OLD',FORM='UNFORMATTED')
          REWIND MEFLU 
      ENDIF 
      READ(NBAND2)    ((VW(M,K),M=1,NZT),K=1,MD1)
      MD2 = MD + MD1
      MD3 = MD2 - 1
      ND = NZPAR(MFR)
      NDD = MZPAR(MFR)
      IZL=MC1*(1+ITPO(MFL))+MD1*(1+ITPO(MFR))
C -----------------------------
c Norm
      INQ(1)=1
c Ekin
      INQ(2)=((IZL-1)*IZL)/2 +1
c Coulomb
      INQ(3)=INQ(2) +1
c Zentral
      INQ(4)=INQ(1)
c P**2
      INQ(5)=INQ(2)
c R**2
      INQ(6)=2
c LS
      INQ(7)=INQ(2)
c Tensor
      INQ(8)=2
c Tensor_p
c   - entries 2 -> ((z-1)z)/2 +1            : \sum_{n<n'}
c   - entries (z(z-1))/2+2 -> (z(z+1))/2+1  : \sum_{n=n'}
      INQ(9)=((IZL-1)*IZL)/2 + IZL + 1
c      write(nout,*)'INQ(2) = ',INQ(2)
c      write(nout,*)'INQ(9) = ',INQ(9)
C -----------------------------
      DO 42 MKC=1, NZOPER
      FOP=1.
      NREB = 0
      IZ=(IZPW-1)*NZLWMA+IZLW
      JZ=(JZPW-1)*NZLWMA+JZLW
      NZAV=MC1+MD1
      IZLURE=1
      IF(LREG(MKC).GT.0) WRITE(NOUT,VARFOR(MKC))
C     OPERATOR 1   2    3    4    5    6    7    8    9  
      GO TO (3008,3002,3003,3008,3002,3005,3002,3004,3002),MKC
3002      NREB = 1
      IZLURE=MC1*(1+ITPO(MFL))+MD1*(1+ITPO(MFR))
      GO TO 3008
3003  IZLURE=2
3004      NZAV=NZAV+1
      GOTO 3008
3005      NZAV=NZAV+2
3008  CONTINUE
      KORR = (NOP(MKC)+1)**2
      NL = MZG(MFL)
      NR = MZG(MFR)
      MKCM=NKCM(MKC)
      IF(JREOB(MKC).EQ.0) GOTO 440
      IF(NREG(JREOB(MKC)).EQ.0) GOTO 440
      READ(NBAND2)    IDUM,NTE,NTE
      IF(NTE.LE.NPDC) GOTO 6029
      WRITE(NOUT,*) ' ZUVIELE PDCS',NTE,' DIMENSION ',NPDC
      STOP 'NPDC'
6029  CONTINUE
      IF(NTE.EQ.0) GOTO 440
      DO 922   MTE = 1,NTE
      READ(NBAND2) NT1(MTE),NT2(MTE),IZT,IMQ,(LCALT(I),I=1,IZT)
     *  ,           (IMV(I),UM(I),I=1,IMQ)
C
      DO 11 I=1,NL
      DO 11 J=1,NR
      DO 11 M=1,MKCM
      U(I,J,M,MTE)= 0.
11    CONTINUE
      DO 12 IK=1,IMQ
      I= IMV(IK)/(NR*MKCM)
      IM=MOD(IMV(IK),NR*MKCM)
      J=IM/MKCM
      M=MOD(IM,MKCM)
12    U(I+1,J+1,M+1,MTE)=UM(IK)
      IF(IZT.EQ.NZT) THEN  
      DO 7 I=1,IZT
7     LC(I,MTE)=LCALT(I)
      GOTO 921
      ENDIF
      DO 177 I=1,NZT
177    LC(I,MTE)=LC(I,MTE-1)
921   CONTINUE
      IF(MOBAUS.EQ.0) GOTO 922
      IF(LREG(MKC).EQ. 0) GOTO 922
      WRITE (NOUT,838) NT1(MTE), NT2(MTE), (LC(K,MTE),K=1,NZT)
 838  FORMAT (10H VON OBER ,20I3)
      IF(MOBAUS.LT.2) GOTO 922
      WRITE (NOUT,839) (((U(NFL,NFR,NKC,MTE),NKC=1,MKCM),NFL=1,NL),
     *       NFR=1,NR)
 839  FORMAT (1P10E12.4)
922   CONTINUE
C
C       READ LUPO ELEMENTE
440   IF(JRELU(MKC).EQ.0) GOTO 441
      IF(IENT(JRELU(MKC)).EQ.0 ) GOTO 441 
      CALL LURE(MKC,ITV2)
      IF(MKC.EQ.1) THEN
      DO 1144, I=1, IZ
       DO 1144, J=1, JZ
1144       WERTNO(I,J)=WERTL(I,J)
       ENDIF
      IF(MKC.EQ.8) THEN
      DO 1145, I=1, IZ
       DO 1145, J=1, JZ
1145       WERTTE(I,J)=WERTL(I,J)
       ENDIF
      IF(LUPAUS.GE.0) WRITE(NOUT,*)' ',ITV2,' LUC-MATRIXELEMENTE'
441   IF(LREG(MKC).EQ.0)  GOTO 6033
      IF (KOM(MKC,MFL,MFR)) 6030,6031,6032
 6030 WRITE(NOUT,6034)
      GO TO 6033
 6031 WRITE(NOUT,6035)
      GO TO 6033
 6032 WRITE(NOUT,6036)
 6033 CONTINUE
      IF(MKC.EQ.4) ITV2=KZHV(2,1)
      IF(MKC.EQ.5) ITV2=KZHV(2,1)
      IF(KOM(MKC,MFL,MFR).EQ.0) GOTO 95
      IF(MFL.NE.MFR)GOTO 97
      NNN=( NZRHO1(MFL)*(NZRHO1(MFL)+1))/2
      GO TO 99
97    NNN=NZRHO1(MFL)*NZRHO1(MFR)
   99 CONTINUE
      IF(LREG(MKC)*NNN.LE.0) GOTO 42
      DO 540 N=1,NNN
      READ (NBAND5) NUML,NUMR,II1,II2,(((DM(K,L,I),K=1,II1),L=1,II2),
     1  I=1,2)
      IF(KOM(MKC,MFL,MFR).LE.0) GOTO 540
      NUML=NUML-IVEK1(MFL)+IVEK(MFL)
      NUMR=NUMR-IVEK1(MFR)+IVEK(MFR)
      WRITE (NBAND1) NUML,NUMR,II1,II2,(((DM(K,L,I),K=1,II1),L=1,II2),
     1  I=1,2)
  540 CONTINUE
      IF(KOM(MKC,MFL,MFR).EQ.1) GOTO 42
      WRITE(NOUT,6037)
6037  FORMAT(' FUER DIESEN OPERATOR WIRD ERGAENZT')
95    IF(IRHO*JRHO.LE.0) GOTO 42
      IF(LREG(MKC).LE.0) GOTO 42
      DO 460 N=1,NDIM
      DO 460 M=1,NDIM
      DM(M,N,1)=.0
  460 DM(M,N,2)=.0
      DO 490 M=1,NZT
  490 LC1(M)=0
      IF (NTE*ITV2.LE.0) GOTO 900
      DO 44 MTE=1,NTE
      IF(NAUS.LT.2) GOTO 1491
      WRITE(NOUT,*) MTE,' TES OBERMATRIXELEMENT'
C
C     FUER SMIN MUESSEN DIESE STATEMENTS BESEITIGT WERDEN
      CLOSE(UNIT=6,STATUS='KEEP')
      OPEN(UNIT=6,FILE='OUTPUT',ACCESS='APPEND')
C
1491  MM=0
      DO 491 M=1,NZT
  491 MM=MM+IABS(LC(M,MTE)-LC1(M))
      IF(MM.EQ.0) GOTO 492
      DO 494 M=1,NZT
  494 LC1(M)=LC(M,MTE)
      DO 470 M=1,NZT
      MM=LC(M,MTE)
  470 VR(MM,1)=VW(M,MD1)
      TS=.0
      TD=.0
      NA= 1
      DO 471 M=1,NZT
      TS=TS+ ABS(VR(M,1)+SVEC(M,NZV))
  471 TD=TD+ ABS(VR(M,1)-SVEC(M,NZV))
      IF(TS*TD.GT.0.000001) NA=0
      DO 50   M = 1,NZV
      DO 50   N = 1,M
      DO 51   K= 1,MD2
   51 QFCR(M,N,K) = .0
      DO 50 K=1,MD1
   50 VR(M,K) = .0
      DO 290  K = 1,MD
      I1 = NGRV(1,K,MFR)
      I2 = NGRV(2,K,MFR) + I1 - 1
      IF(NGRV(2,K,MFR).LE.1)GOTO 290
      FZZ = 1./ DBLE(NGRV(2,K,MFR))
      I3=I2-1
      DO 52  L1 = I1,I3
      I4=L1+1
      DO 52  L2 =I4,I2
      L3 = LC(L1,MTE)
      L4 = LC(L2,MTE)
      DO 52  M = 1,NZV
      DO 52  N = 1,NZV
      MM=MIN0(M,N)
      NN=MAX0(N,M)
   52 QFCR(NN,MM,K) = QFCR(NN,MM,K) + (RVEC(M,L3)-RVEC(M,L4))*
     1(RVEC(N,L3)-RVEC(N,L4)) *FZZ
  290 CONTINUE
      DO 53  K = 2,MD
      KI = MD1 + K
      DO 100   M = 1,NZT
      MM = LC(M,MTE)
      DO 100  N = 1,NZV
  100 VR(N,K-1) = VR(N,K-1) + VW(M,K-1) *RVEC(N,MM)
      DO 53   M = 1,NZV
      DO 53   N = 1,NZV
      MM=MIN0(M,N)
      NN=MAX0(N,M)
      QFCR(NN,MM,KI ) = QFCR(NN,MM,KI ) + VR(M,K-1)*VR(N,K-1)
   53 CONTINUE
  492 CONTINUE
      DO 54  M = 1,NZV
      UR(M) = RVEC(M,NT1(MTE)) - RVEC(M,NT2(MTE))
      WR(M) = SVEC(NT1(MTE),M) - SVEC(NT2(MTE),M)
      DO 54  N = 1,NZV
   54 QFO(M,N)=.0
      DO 55   M = 1,NZV
      DO 55   N = 1,NZV
      MM=MIN0(M,N)
      NN=MAX0(N,M)
      QFO(NN,MM) = QFO(NN,MM) + UR(M)*UR(N)
   55 CONTINUE
      DO 80 IPOT=1, NZPOT(MKC)
      FAK=WECPOT(IPOT,1,MKC)
       POWE= WECPOT(IPOT,2,MKC)
      DO 82 M=1,NL
      DO 82 N=1,NR
      UU(M,N)=.0
      DO 81 NKC=1,MKCM
   81 UU(M,N)=UU(M,N)+WECPOT(IPOT,NKC+2,MKC)*U(M,N,NKC,MTE)*FOP
      if(abs(uu(m,n)).lt. 1.e-10) uu(m,n)=0.
   82 CONTINUE
      DO 60   KPAR = 1,NC
      DO 62   M = 1,NZV
      DO 62   N = 1,M
   62 POL (M,N) = .0
      DO 64   M = 1,NZV
      IF(MC3.LE.0) GOTO 64
      DO 63   K = 1,MC3
   63 POL (M,M)=POL (M,M) + CPAR(K,KPAR,MFL)*QFCL(M,M,K)
   64 CONTINUE
       DO 70 LPAR=1,ND
      I=0
      DO 101 M=1,IRHO
      KSL= NUM(1,M,MFL)
      KLL= NUM(2,M,MFL)
      KPL=NUM(4,M,MFL)
      JPL=(KPL-1)*NZLWMA+KLL
      NUML= NUM(3,M,MFL)
      TS = COF(KPAR,M,MFL)
      IF (ABS(TS).LT.1.E-10) GOTO 101
      MADL = (M-1) * IK1
      DO 105 N=1,JRHO
      KSR= NUM(1,N,MFR)
      KLR= NUM(2,N,MFR)
      KPR=NUM(4,N,MFR)
      JPR=(KPR-1)*NZLWMA+KLR
      NUMR= NUM(3,N,MFR)
      IF (NUML.LT.NUMR) GOTO 105
      IF(WERTL(JPL,JPR).NE.1.) GOTO 105
       A = TS * UU(KSL,KSR)*COF(LPAR,N,MFR)
      IF(ABS(A).LT.1.E-20) GOTO 105
      MADR = (N-1) * JK1
      IF (I.LT.NDIM5) GOTO 110
      WRITE (NOUT,111) I
 111  FORMAT ('0NSH ZU KLEIN', I4)
      STOP
 110  I = I + 1
      NSH1(I) = NDIM * (MADR-1) + MADL
      NSH2(I) = NDIM4 * (JPR-1) + JPL
      SH(I) = A
 105  CONTINUE
 101  CONTINUE
      NSH = I
      IF (NSH.EQ.0) GOTO 70
      DO 72   M = 1,NZV
      DO 72   N = 1,NZV
   72 POR(M,N) = .0
      DO 74  M = 1,NZV
      DO 74  N = M,NZV
      IF(MD3.LE.0) GOTO 74
      DO 73  K = 1,MD3
   73 POR(N,M)=POR(N,M)+CPAR(K,LPAR,MFR)*QFCR(N,M,K)
   74 CONTINUE
      DO 67 M=1,NZV
      DO 67  N = M,NZV
   67 POLL(N,M)=POL(N,M)+
     1  WECPOT(IPOT,2,MKC)*QFO(N,M)
      DO 76 LPARR=1,NDD
      DO 77 M=1,NZV
      DO 77 N=M,NZV
   77 PORR(N,M)=POR(N,M)+RPAR(LPARR,MFR)*QFCR(N,M,MD2)
      CALL SCORR(POLL,PORR,QFO,   NA,FAK)
   76 CONTINUE
C      LOOP RADIALWEITEN RECHTS
   70 CONTINUE
C     LOOP INNNERE WEITEN RECHTS
   60 CONTINUE
C      LOOP INNERE WEITEN LINKS
   80 CONTINUE
C       LOOP POTENTIAL
   44 CONTINUE
C       LOOP OBER
  900 CONTINUE
      DO 480 M=1,IRHO
      NUML=NUM(3,M,MFL)
      DO 481 N=1,JRHO
      NUMR=NUM(3,N,MFR)
      IF(NUML.LT.NUMR) GOTO 481
      IF (NUM(5,M,MFL)*NUM(5,N,MFR).GT.0) GOTO 482
C     HIER WERDEN DIE BASISVEKTOREN UEBERSPRUNGEN
      M1=(M-1)*IK1+1
      M2=M*IK1
      N1=(N-1)*JK1+1
      N2=N*JK1
      II1 = 1
      A = 0.
      DO 510 I=1,2
      DO 510 L=N1,N2
      DO 510 K=M1,M2
 510  A = A + ABS(DM(K,L,I))
      IF(A.GT.0.) GOTO512
      WRITE (NBAND1) NUML,NUMR,II1,II1,A,A
      GOTO 481
512   WRITE(NBAND1) NUML,NUMR,IK1,JK1,(((DM(K,L,I),K=M1,M2),L=N1,N2),
     1 I=1,2)
      IF (NAUS.EQ.0) GOTO 481
      WRITE (NOUT,1002) NUML, NUMR, IK1, JK1
      IF(NAUS.LT.1) GOTO 481
      WRITE (NOUT,1021) (((DM(K,L,I), K=M1,M2),L=N1,N2),I=1,2)
1021  FORMAT(1X,10E12.5)
482   IF(NUM(5,M,MFL)*NUM(5,N,MFR).GT.0) WRITE(NOUT,*) 'M,N',M,N,
     *  ' NUM5', NUM(5,M,MFL),NUM(5,N,MFR)
  481 CONTINUE
  480 CONTINUE
C      LOOP BASISVECTOR
C
C
      ISTOPP=ISTOPP+1
      IF (ISTOP.GT.0.AND.ISTOPP.GE.ISTOP) STOP 777
C     HIER KANN PROGRAMM NACH BERECHNUNG VON ISTOP OPERATOREN GESTOPPT
C     WERDEN
C
C     FUER SMIN MUESSEN DIESE STATEMENTS BESEITIGT WERDEN
      CLOSE(UNIT=6,STATUS='KEEP')
      CLOSE(UNIT=10,STATUS='KEEP')
      OPEN(UNIT=10,FILE='QUAOUT',ACCESS='APPEND',FORM='UNFORMATTED')
      OPEN(UNIT=6,FILE='OUTPUT',ACCESS='APPEND')
   42 CONTINUE
C        LOOP OPERATOREN
   40 CONTINUE
      WRITE(NOUT,3011)
3011  FORMAT(//,' ENDE DER RECHNUNG VON QUAF')
      CLOSE(UNIT=5,STATUS='KEEP')
      CLOSE(UNIT=9,STATUS='KEEP')
      CLOSE(UNIT=12,STATUS='KEEP')
CC    RETURN
C     FUER SMIN AKTIVIEREN UND STOP DEAKTIVIEREN
      STOP
 6100 FORMAT(/31H ES WIRD VOELLIG NEU GERECHNET /)
 6034 FORMAT(34H FUER DIESEN OPERATOR WIRD ERSETZT /)
 6035 FORMAT(40H FUER DIESEN OPERATOR WIRD NEU GERECHNET /)
 6036 FORMAT(34H FUER DIESEN OPERATOR WIRD KOPIERT /)
7201  WRITE(NOUT,7202) NKOR
7202  FORMAT(' ZUVIELE KORRELATIONSFUNKTIONEN',I5)
1051  FORMAT(1X,'DIESER BASISVEKTOR WIRD NICHT NEU GERECHNET')
      END
      SUBROUTINE LURE(MKC,ITV2)
      IMPLICIT REAL*8 (A-H,O-Z)
C     LURE LIEST MATRIXELEMENTE AUS LUDWIG EIN
C
      INCLUDE 'par/QUAF_EFT'
C
      PARAMETER (NZAVMA=2*NZCMAX-1, NDIM4=NZPOMA*NZLWMA,
     *           NZLRH=(2*NZCMAX-3)*(NZCMAX-1),
     *   NZLREC=2*NZCMAX  + NZLRH+(NZLRH*(NZLRH+1))/2)
C
      COMMON /LUP/ KVK(NDIM1), JQ(NDIM1), INDPO(NDIM1),
     *    MVK(NDIM1,NZIQMA), EPO(NDIM1), WERTL(NDIM4,NDIM4),
     *    IZ,JZ, KZHV(2,NZLREC+1), LUPAUS, IQM(NZLREC+1),
     *    KZHX(0:NZIQMA,NZLREC+1)
C
      COMMON /LUR/ IENT(NZOPLU), NBAND3
C
      COMMON /BEG/ POWE, IZLURE, INQ(NZOPER),NAUS
C
      ITV2=0
      IU=2
C    OPERATOR 1  2   3   4   5   6   7   8    9
      GOTO (10, 60, 40,400, 400, 20, 20, 20, 60),MKC
C
10    IU=1
20    DO 30, I=1, IZ
       DO 30, J=1, JZ
        WERTL(I,J)=0.
30    CONTINUE
60    CONTINUE
C    OPERATOR 1  2   3   4   5   6   7   8   9
      GOTO(  61, 61,446,400,400,61, 61, 61, 61),MKC
40    IU=INQ(2) +1
      GOTO 61
C
52    IU=3
61    CONTINUE
      DO 200, IIZ=IU, INQ(MKC)
       READ (NBAND3) K1ZAHL, IQMH
       IF (IQMH.GT.NZIQMA) GOTO 445
       IF (LUPAUS.GT.0) WRITE (NOUT,1000) IIZ, K1ZAHL, IQMH
       KZHV(2,IIZ)=K1ZAHL
       IF (IIZ.EQ.1) KZHV(1,1)=0
       IF (IIZ.NE.1) KZHV(1,IIZ)=KZHV(1,IIZ-1)+KZHV(2,IIZ-1)
       KZAHL=KZHV(1,IIZ)+K1ZAHL
       IF (K1ZAHL.EQ.0) GOTO 200
       IQMH=MAX0(IQMH,1)
       IQM(IIZ)=IQMH
       IF (KZAHL.GT.NDIM1) GOTO 444
       K2ZAHL=KZAHL-K1ZAHL+1
       READ (NBAND3) (JQ(KW),INDPO(KW),EPO(KW),(MVK(KW,IW),
     *                IW=1,IQMH), KW=K2ZAHL,KZAHL)
C    SORTIEREN NACH ANZAHL DER SIGMA FAKTOREN
        CALL ORDSRT(IIZ,K2ZAHL,KZAHL)
C
       CALL FAPOR(K2ZAHL,KZAHL)
200   CONTINUE
C
      ITV2=KZAHL
c --- for r^2, LS and tensor(_p), correct ITV2
      IF (MKC.GE.6) ITV2=ITV2-KZHV(2,1)
C
400   RETURN
C
444   WRITE (NOUT,1001) IIZ, KZAHL, NDIM1
      STOP 444
445   WRITE (NOUT,1002) IIZ, IQMH, NZIQMA
      STOP 445
446   STOP 'MKC SPRINGT FALSCH'
C
1000  FORMAT(/,I3,'. RECORD AUS LUDWIG:',
     *       ' RECORDLAENGE',I7,'   IQM',I5)
1001  FORMAT(/,1X,'RECORD AUS LUDWIG ZU LANG',/,1X,
     *       'IIZ, KZAHL, NDIM1:',3I8)
1002  FORMAT(/,1X,'ZU VIELE SIGMAFAKTOREN',/,1X,
     *       'IIZ, IQM, NZIQMA:',3I4)
      END
      SUBROUTINE FAPOR(IA,IE)
      IMPLICIT REAL*8 (A-H,O-Z)
C     FAPOR REPRODUZIERT DIE DREIMPULS- UND POLYNOMSTRUKTUR
C
      INCLUDE 'par/QUAF_EFT'
C
      PARAMETER (NZAVMA=2*NZCMAX-1, NDIM4=NZPOMA*NZLWMA,
     *           NZLRH=(2*NZCMAX-3)*(NZCMAX-1),
     *   NZLREC=2*NZCMAX  + NZLRH+(NZLRH*(NZLRH+1))/2)
C
      COMMON /LUP/ KVK(NDIM1), JQ(NDIM1), INDPO(NDIM1),
     *    MVK(NDIM1,NZIQMA), EPO(NDIM1), WERTL(NDIM4,NDIM4),
     *    IZ,JZ, KZHV(2,NZLREC+1), LUPAUS, IQM(NZLREC+1),
     *    KZHX(0:NZIQMA,NZLREC+1)
C
      COMMON /CSH/ NSH1(NDIM5), NSH2(NDIM5), SH(NDIM5), NSH
C
      IF(LUPAUS.EQ.0) GOTO 100
      WRITE(NOUT,10) IA,IE
10    FORMAT(' VON LUDWIG ELEMENTE VON',I8,' BIS ',I10)
      IF(LUPAUS.LT.2) GOTO 100
      DO 15 I=IA,IE
15    WRITE(NOUT,20) JQ(I),INDPO(I),EPO(I),(MVK(I,J),J=1,JQ(I))
20    FORMAT(I5,' INDEX',I10,' EPO ',E12.5,' MVK',19I3)
100   DO 1 I=IA,IE
      KPL=INDPO(I)/100000+1
      KPR=MOD(INDPO(I)/10000,10)+1
      LL=MOD(INDPO(I)/100,100)+1
      LR=MOD(INDPO(I),100)+1
      LPL=(KPL-1)*NZLWMA+LL
      LPR=(KPR-1)*NZLWMA+LR
      WERTL(LPL,LPR) = 1.
       L = NDIM4 * (LPR-1) + LPL
      KVK(I) = L
    1 CONTINUE
      RETURN
      END
      SUBROUTINE SCORR(POL,POR,Q,NA,F)
      IMPLICIT REAL*8 (A-H,O-Z)
C     SCORR BERECHNET DIE KORRELATIONSFUNKTION
C
      INCLUDE 'par/QUAF_EFT'
C
      PARAMETER (NZVMAX=NZTMAX-1, NDIM4=NZPOMA*NZLWMA)
C
      COMMON /SC/ ABC(4), ABD(4), ABE(4), KORR, NZT
C
      COMMON  MKC, NZV, QO(NZVMAX,NZVMAX), QOR(NZVMAX,NZVMAX),
     *        VZ(NZVMAX,NZVMAX), WERT(NDIM4,NDIM4), UR(NZVMAX)
C
      DIMENSION Q(NZVMAX,NZVMAX),POL(NZVMAX,NZVMAX),POR(NZVMAX,NZVMAX)
C
      DO 7 N=1,NZV
      DO 7 M=1,NZV
      QO(N,M)=0.
7     QOR(N,M)=0.
      DO 100K=1,KORR
      FF=F*ABC(K)
       GOTO (30,5,2,2,5,2,2,2,2),MKC
   30 IF(K.EQ.1) GOTO 8
      FF=FF* DBLE((NZT*NZV)/2)
      GO TO 4
    5 IF(K.EQ.1) GOTO 8
      FF = FF* DBLE(NZT)/2.
      IF(K-4)      1,8,8
    2 IF(MKC.GE.6) GOTO 8
    4 GO TO (8,1,11,8) ,K
   11 FF=2.*FF
    8 DO 10  M = 1,NZV
      DO 10  N = M,NZV
      QOR(N,M)=POR(N,M)+ABE(K)*Q(N,M)
   10 QO(N,M)=POL(N,M)+ABD(K)*Q(N,M)  + QOR(N,M)
      IF(NA.EQ.0) GOTO 26
      IF( ABS(UR(NZV)).GE.0.0000001)GOTO 24
      NB = 1
      GO TO 22
   24 IF(MKC.GT.2) GOTO 26
       IF(K.NE.1) GOTO 26
        NB=1
      GO TO 22
   26 NB=0
   22 CONTINUE
      CALL BEGRI(NB,FF)
    1 CONTINUE
100   CONTINUE
      RETURN
      END
      SUBROUTINE HAUPT
      IMPLICIT REAL*8 (A-H,O-Z)
C     HAUPT FUEHRT HAUPTACHSENTRANSFORMATION DURCH
C     TRANSFORMATION IN VZ, HAUPTACHSENWERTE IN QO
C
      INCLUDE 'par/QUAF_EFT'
      PARAMETER (NZVMAX=NZTMAX-1)
C
      COMMON  MKC, NZV, QO(NZVMAX,NZVMAX), QOR(NZVMAX,NZVMAX),
     *        VZ(NZVMAX,NZVMAX)
C
      DO 1   K = 1,NZV
      VZ(K,K) = 1.
      IF(NZV-K)   1,1,2
    2 A = .5/QO(K,K)
      K1 = K + 1
      DO 7   M = K1,NZV
      VZ(M,K) = .0
      B = A*QO(M,K)
      DO 5   L = 1,K
    5 VZ(M,L) = VZ(M,L) - B*VZ(K,L)
      QO(M,M) = QO(M,M) - B*B*QO(K,K)
      IF(NZV-M)   7,7,6
    6 M1 = M + 1
      DO 4   N = M1,NZV
    4 QO(N,M) = QO(N,M) - A*QO(M,K)*QO(N,K)
    7 CONTINUE
    1 CONTINUE
      RETURN
      END
      SUBROUTINE BEGRI(NB,FF1)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C
      INCLUDE 'par/QUAF_EFT'
C
C
      PARAMETER (NZAVMA=2*NZCMAX-1, NZVMAX=NZTMAX-1,
     *           NDIM4=NZPOMA*NZLWMA, NZLRH=(2*NZCMAX-3)*(NZCMAX-1),
     *   NZLREC=2*NZCMAX  + NZLRH+(NZLRH*(NZLRH+1))/2)
C
      COMMON /BIG/ DM(NDIM,NDIM,2)
C
      COMMON /BEG/ POWE, IZLURE, INQ(NZOPER),NAUS
C
      COMMON /CSH/ NSH1(NDIM5), NSH2(NDIM5), SH(NDIM5), NSH
C
      COMMON  MKC, NZV, QO(NZVMAX,NZVMAX), QOR(NZVMAX,NZVMAX),
     *        VZ(NZVMAX,NZVMAX), WERT(NDIM4,NDIM4), UR(NZVMAX),
     *        LPARR, MC1, MD1, MFL, NCC, NREB, NZAV, NZV1, PHI2,
     *        RPAR(MZPARM,NZFMAX), VR(NZTMAX,NZCMAX-1),
     *        WR(NZTMAX)
C
      DIMENSION P(NZAVMA,NZVMAX), BETA(NZVMAX), RHO(NZVMAX),
     *          S((NZAVMA*(NZAVMA+1))/2+1), Y(NZAVMA),
     *          GAM(NZAVMA), ZZ(NZAVMA),
     *          ZH(NZAVMA), ZW(NZVMAX), 
     *          SS(NZAVMA*(NZAVMA+1)+2), HX(NZAVMA-1,NZAVMA-1)
      DIMENSION H(NZLREC+1), RT(NZVMAX), RTH(NZVMAX),
     *          YH(NZAVMA), ZZH(NZAVMA), C(NZAVMA,NZAVMA,NZAVMA,NZAVMA)
C
      DIMENSION WERTT(NDIM4*NDIM4), DMM(NDIM*NDIM,2)
C
      EQUIVALENCE (WERT,WERTT), (DM,DMM)
C
C
C       WR = KOORDINATEN DER WW-TEILCHEN
C
      G= .0
      G0=0.
      DO 80   M = 1,NZV
      RT(M)=0.
      RTH(M)=0.
      RHO(M) = .0
      DO 80   N = 1,NZAV
   80 P(N,M) = 0.
      INZ1=(NZAV*(NZAV+1))/2+1
      DO 81 M=1,INZ1
81    S(M)=0.
      IF(NREB.EQ.0) GOTO 82
      DO 84   N = 1,NZAV
      YH(N)=0.
      ZZH(N)=0.
      GAM(N) = .0
      IF(N.LT.MC1+1)  GOTO 84
      DO 86   K = 1,NZV
   86 GAM(N) = GAM(N) + VR(K,N-MC1)*WR(K)
C       TRANSFORMATION DER RELATIV-VECTOREN RECHTS AUF JACOBI
C      UND SKALARE MULTIPLIKATION MIT TRANSFORMATION DER
C      WECHSELWIRKENDEN TEILCHEN AUF JACOBI
   84 CONTINUE
      DO 87   M = 1,NZV
      DO 87   K = 1,NZV
   87 RHO(M) = RHO(M) + WR(K)*(QOR(K,M)+QOR(M,K))
C      RHO = TRANSFORMATION DER WW-TEILCHEN AUF JACOBI* RHO-MATRIX RECHT
      GRHO= 0.
      WR2=0.
      DO 85 K=1,NZV
      WR2=WR2 + WR(K)**2
85    GRHO=GRHO + WR(K)* RHO(K)
C     GRHO IST RHO * WW-TEILCHEN
      IF(NAUS.LT.3) GOTO 82
      WRITE(NOUT,*) ' QOR',((QOR(N,M),N=1,NZV),M=1,NZV)
      WRITE(NOUT,*) ' GAM ',(GAM(N),N=1,NZAV)
      WRITE(NOUT,*) ' RHO ',(RHO(N),N=1,NZV)
      WRITE(NOUT,*) ' WR ',(WR(N),N=1,NZV)
      WRITE(NOUT,*) ' WR**2 ',(WR(N)*WR(N),N=1,NZV)
   82 CONTINUE
      IF(NAUS.GT.2) 
     +WRITE(NOUT,*) ' QO',((QO(N,M),N=1,NZV),M=1,NZV)
      CALL HAUPT
      IF(NAUS.GT.2) 
     +WRITE(NOUT,*) ' QO',(QO(N,N),N=1,NZV)
      FFF=1.
      IF(NZV1.EQ.0) GOTO 71
       DO 1   M = 1,NZV1
      BETA(M)=1./ SQRT(QO(M,M))
    1 FFF=PHI2*BETA(M)*FFF
   71 CONTINUE
      BETA(NZV) = 1.
      DO 2 N=1,MC1
      NN=NZV-MC1+N
      DO 2 M=NN,NZV
    2 P(N,M)=VZ(M,NN)*BETA(M)
C      VZ(M,N) TRANSFORMATIONSMATRIX VON S(N) AUF T(M)
C     VZ(M,N)=T(N,M) EQ 7.9
C      P(M,N)=P(M,N) EQ 7.11
      DO 4 N=1,MD1
      NN=MC1+N
      DO 4 M=1,NZV
      DO 6 K=1,M
    6 P(NN,M)=VR(K,N)*VZ(M,K)+P(NN,M)
    4 P(NN,M)=P(NN,M)*BETA(M)
C      P= TRANSFORMATIONS-MATRIX VON RELATIV AUF DIAGONALKOORDINATEN T
C      BEREITS DIVIDIERT DURCH WURZEL BETA
      GOTO (10,10,7,10,10,710,10,7,10), MKC
C --- R**2
  710 DO 711 M=1,NZV
      DO 712 K=1,M
      P(NZAV-1,M)=P(NZAV-1,M)+UR(K)*VZ(M,K)
  712 P(NZAV,M)=P(NZAV,M)+UR(K)*VZ(M,K)
      P(NZAV-1,M)=P(NZAV-1,M)*BETA(M)
  711 P(NZAV,M)=P(NZAV,M)*BETA(M)
      GOTO 10
C --- TENSOR
    7 DO 8 M=1,NZV
      DO 9 K=1,M
    9 P(NZAV,M)=P(NZAV,M)+UR(K)*VZ(M,K)
    8 P(NZAV,M)=P(NZAV,M)*BETA(M)
   10 CONTINUE
      DO 3  M = 1,NZAV
    3 ZH(M) = P(M,NZV)
      DO 5   M = 1,NZV
    5 ZW(M) = VZ(NZV,M)
      IF (NZV1.EQ.0) GOTO 14
      DO 11 M=1,NZV1
      DO 11 N=1,M
   11 VZ(M,N)=VZ(M,N)*BETA(M)
C     VZ DIVIDIERT DURCH WURZEL BETA
      I=0
      DO 12 M=1,NZAV
      DO 12 N=M,NZAV
      I=I+1
      DO 12   K = 1,NZV1
   12 S(I)=S(I)+P(N,K)*P(M,K)
C      S= SIGMA-FAKTOREN
C     SIGMA(N,N') EQ 7.14
      IF (MKC.NE.3)  GOTO 14
      I=I+1
      DO 16 K=1,NZV1
   16 S(I)=S(I)+P(NZAV,K)**2
   14 CONTINUE
      IF(NREB.EQ.0) GOTO 88
      IF (NZV1.EQ.0) GOTO 46
      DO 40 K=1,NZV1
      DO 41 M=1,K
      RT(K)=RT(K)+RHO(M)*VZ(K,M)
   41 RTH(K)=RTH(K)+WR(M)*VZ(K,M)
   40 G=G+RT(K)*RT(K)
      G0=G
      DO 62 N=1,NZAV
      DO 62 K=1,NZV1
      ZZH(N)=ZZH(N) + RTH(K)*P(N,K)
62    YH(N)=YH(N) + RT(K)*P(N,K)
  46  GG = G - 2.*GRHO
      GOTO (88,88,88,88,47,88,88,88,88), MKC
47    G1=0.
       G2=0.
       IF(NZV1.EQ.0) GOTO 88
      DO 140 K=1,NZV1
      G1=G1+RT(K)*RTH(K)
140    G2=G2+RTH(K)*RTH(K)
   88 CONTINUE
      DO 170  KPARR = 1,NCC
      BETA(NZV) = 1./ SQRT(QO(NZV,NZV)+RPAR(KPARR,MFL))
      FFW = FFF *PHI2*BETA(NZV)
      FF=FFW**3*FF1
      IF(NAUS.GT.2) WRITE(NOUT,*) 'BETA',(BETA(K),K=1,NZV),' FF1,FF ',
     *   FF1,FF
      DO 91   M = 1,NZAV
   91 P(M,NZV) = ZH(M)*BETA(NZV)
      DO 92    M = 1,NZV
   92 VZ(NZV,M) = ZW(M)*BETA(NZV)
      IF(NAUS.LT.3) GOTO 136
      DO 132 M=1,NZV
132   WRITE(NOUT,*) ' P ',(P(N,M),N=1,NZAV)
      DO 133 M=1,NZV
133   WRITE(NOUT,*) ' T ',(VZ(N,M),N=1,NZV)
136   I = 0
      DO 93   M = 1,NZAV
      DO 93   N = M,NZAV
      I = I + 1
   93 SS(I) = 2.*(S(I) + P(N,NZV)*P(M,NZV))
      SS(I+1) = 2.*(S(I+1) + P(NZAV,NZV)**2)
      I = (NZAV*(NZAV-1))/2
      IF(NAUS.GT.2) WRITE(NOUT,*)' SS',(SS(IH),IH=1,I+NZAV),' FF',FF
      IF(NREB.GT.0) GOTO 19
      G = FF
      H(1)=G
      IF(MKC.EQ.6 .OR. MKC.EQ.8) H(2)=G
      IF (MKC.NE.3) GOTO 33
      I=(NZAV*(NZAV+1))/2
      IC = I+1
      CC = 1. / SS(IC)
      G = G * SQRT(2.*CC)
      H(INQ(3)) = G
      DO 34  M=1,NZAV
      DO 34  N=M,NZAV
      IC = IC+1
      IC1 = M*NZAV - (M*(M-1))/2
      IC2 = N*NZAV - (N*(N-1))/2
34    SS(IC) = SS(IC1) * SS(IC2) * CC
      SS(IC+1) = SS(I+1)
33    CONTINUE
c --- mat berechnung fuer nreb=0 ,i.e. norm,coulomb,central,r**2,tensor
      CALL MAT(H,SS,INQ(MKC))
      GO TO 70
19    RT(NZV)=0.
      RTH(NZV)=0.
      DO 96    M = 1,NZV
      RT(NZV) = RT(NZV) + RHO(M)*VZ(NZV,M)
   96 RTH(NZV) = RTH(NZV) + WR(M)*VZ(NZV,M)
      IF(NAUS.GT.2) WRITE(NOUT,*) ' RT' ,(RT(M),M=1,NZV)
      IF(NAUS.GT.2) WRITE(NOUT,*) ' RTH' ,(RTH(M),M=1,NZV)
      DO 24 N=1,NZAV
      Y(N) = YH(N) + RT(NZV)*P(N,NZV)
24    ZZ(N) = ZZH(N) + RTH(NZV)*P(N,NZV)
c Ekin
      IF(MKC.EQ.2) GOTO 196
c LS
      IF(MKC.EQ.7) GOTO 32
      G0P=G0+RT(NZV)*RT(NZV)
      G1P=G1+RT(NZV)*RTH(NZV)
      G2P=G2+RTH(NZV)*RTH(NZV)
c --- Faktor 0.5 kommt von Antisymmetriesierer, auch in Z_nn'
      IF(MKC.EQ.5) G=.5*(GG+RT(NZV)*RT(NZV))+2.*POWE*(G1P
     1               -2.+POWE*2.*G2P)
      GOTO 97
196   G = GG + RT(NZV)*RT(NZV)
97    II= 0
      H(1)=1.5*FF*G
      II= 1
98    DO 44 M=1,NZAV
      DO 44 N=1,NZAV
   44 HX(M,N)=2.*FF*(Y(M)-2.*GAM(M))*(Y(N)-2.*GAM(N))
c      DO 45 M=1,NZAV
c      DO 45 N=1,NZAV
c   45 if(HX(M,N).ne.HX(N,M)) write(nout,*)'H_nm neq H_mn fuer nm=',N,M
      GOTO(30,52,30,30,150,30,30,30,311), MKC
52    DO 144 M=2,IZLURE
      MXH=(M-2)/NZAV
      MH=M-1-MXH*NZAV
      DO 144 N=M,IZLURE
      NXH=(N-1)/NZAV
      NH=N-NXH*NZAV
      II=II+1
144   H(II)=HX(MH,NH)
c      write(nout,*)'#Elemente in H:',II,' Op. Nr.:',MKC
145   CONTINUE
c --- for operators 14,15 Z_nn has to be considered
      IF(MKC.EQ.9) THEN
      DO 1444 M=1,IZLURE
      II=II+1
1444  H(II)=HX(M,M)
c      write(nout,*)II,'EINTRAEGE IN H GESCHRIEBEN'
      ENDIF
148   IF(NAUS.LT.3) GOTO 149
      WRITE(NOUT,*) 'WR2 ',WR2,' GRHO ',GRHO,' FF ',FF
      WRITE(NOUT,*) ' G0P ',G0P,' G1P ',G1P,' G2P ',G2P
      WRITE(NOUT,*) ' Y -2GAM',(Y(N)-2.*GAM(N),N=1,NZAV)
      WRITE(NOUT,*) ' ZZ ',(ZZ(N),N=1,NZAV)
      WRITE(NOUT,*) ' H ',(H(N),N=1,II)
      WRITE(NOUT,*) ' S ',(SS(N),N=1,(NZAV*(NZAV+1))/2)
149   CALL MAT(H,SS,INQ(MKC))
      GO TO 70
32    DO 51 M=1,NZAV
      DO 51 N=1,NZAV
   51 HX(M,N)=FF*(ZZ(M)*(-.5*Y(N)+GAM(N))-ZZ(N)*(-.5*Y(M)+GAM(M)))
      II= 1
C     LS  
      GO TO 52
150   DO 154 M=1,NZAV
      DO 154 N=1,NZAV
154   HX(M,N)=FF*4.*POWE*(ZZ(M)*(.5*Y(N)-GAM(N))+ZZ(N)*(.5*Y(M)-GAM(M))
     1  +2.*POWE*ZZ(M)*ZZ(N))+.5*HX(M,N)
C     P**2
      GOTO 52
c --------------------------- tensor_p a --------------------------
311   DO 511 M=1,NZAV
      DO 511 N=1,NZAV
c -- faktor 2 von nn'+n'n, 0.25 unterschied zu hx_kin : HX(M,N)=2.*FF*(Y(M)-2.*GAM(M))*(Y(N)-2.*GAM(N))
  511 HX(M,N)=FF*( 2.*0.25*2.*(Y(M)-2.*GAM(M))*(Y(N)-2.*GAM(N))
     1        +2.*POWE*(ZZ(M)*(2.*POWE*ZZ(N)+Y(N)-2.*GAM(N))
     2                    +ZZ(N)*(2.*POWE*ZZ(M)+Y(M)-2.*GAM(M))) )
      II= 1
      GOTO 52
c -----------------------------------------------------------------
160   FR=1.
      IF(MKC.EQ.11) FR=-0.5
      DO 164 N=1,NZAV
      DO 164 M=N,NZAV
164   HX(N,M)=FR*(FF/2.*(
     1  ZZ(N)*ZZ(M)*(2.*GRHO - 1.*G0P)
     2  +(G1P-WR2)*(ZZ(N)*(Y(M)-2.*GAM(M)) + ZZ(M)*(Y(N)-2.*GAM(N)))
     3  -G2P*(Y(M)-2.*GAM(M))*(Y(N)-2.*GAM(N)) ) )
      DO 166 N=1,NZAV
      DO 166 M=1,NZAV
      IF(M.EQ.N) GOTO 166
      NMIN=MIN(N,M)
      DO 165 NP=NMIN,NZAV
      DO 165 MP=NMIN,NZAV
      C(N,M,NP,MP)=-(FF/8.)*(ZZ(N)*ZZ(NP)*(Y(M)-2.*GAM(M))*
     1            (Y(MP)-2.*GAM(MP)) )
165   CONTINUE
166   CONTINUE
C     L**2,LS**2 SKALAR
      IF(MKC.LT.11) GOTO 52
C     LS**2 TENSOR
      II=2
      DO 168 N=1,NZAV
      DO 168 M=N,NZAV
      II=II+1
168   H(II)= HX(N,M)
      GOTO 145
70    CONTINUE
      I0 = NDIM * LPARR + KPARR
      DO 100 M=1,NSH
      I2 = NSH2(M)
      CC= SH(M) * WERTT(I2)
      IF (CC.EQ.0.) GOTO 100
      I1 = NSH1(M) + I0
      IF (NB) 110,110,111
C       DMM(.,.,2) ENTHAELT ALLE BEITRAEGE
C       DMM(.,.,1) ENTHAELT NUR BEITRAEGE FUER NB=0
 110  DMM(I1,1) = DMM(I1,1) + CC
 111  DMM(I1,2) = DMM(I1,2) + CC
      IF(NAUS.GT.1) WRITE(NOUT,120) M,I1,I2,SH(M),CC,DMM(I1,1),DMM(I1,2)
120   FORMAT(' M,I1,I2,SH,CC,DMM1,2 ',3I5,E14.6,3E20.14)
  100 CONTINUE
  170 CONTINUE
      RETURN
   30 CONTINUE
      STOP '30'
      END
      SUBROUTINE MAT(H,S,NQ)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C
      INCLUDE 'par/QUAF_EFT'
C
      PARAMETER (NZAVMA=2*NZCMAX-1, NZVMAX=NZTMAX-1,
     *           NDIM4=NZPOMA*NZLWMA, NZLRH=(2*NZCMAX-3)*(NZCMAX-1),
     *   NZLREC=2*NZCMAX  + NZLRH+(NZLRH*(NZLRH+1))/2)
C
      COMMON /LUP/ KVK(NDIM1), JQ(NDIM1), INDPO(NDIM1),
     *    MVK(NDIM1,NZIQMA), EPO(NDIM1), WERTL(NDIM4,NDIM4),
     *    IZ,JZ, KZHV(2,NZLREC+1), LUPAUS, IQM(NZLREC+1),
     *    KZHX(0:NZIQMA,NZLREC+1)
C
      COMMON  MKC, NZV, QO(NZVMAX,NZVMAX), QOR(NZVMAX,NZVMAX),
     *        VZ(NZVMAX,NZVMAX), WERT(NDIM4,NDIM4), UR(NZVMAX)
C
      DIMENSION S(NZAVMA*(NZAVMA+1)+2), H(NZLREC+1)
      DIMENSION WERTT(900),F(NDIM1)
      EQUIVALENCE (WERT,WERTT)
      DO 4   LR = 1,JZ
      DO 4   LL = 1,IZ
    4 WERT(LL,LR) = .0
      NU=1
      NN=NQ
      GO TO(13,13,10,13,13,11,11,11,11),MKC
   10 NU = NQ
      GO TO 13
   11 NU = 2
13    IF(LUPAUS.GT.3) THEN
      WRITE(NOUT,*) ' H ',(H(N),N=NU,NN)
      WRITE(NOUT,*) ' S ',(S(N),N=1,12)
      ENDIF
      DO 1 N=NU,NN
      K3ZAHL = KZHV(2,N)
      IF(K3ZAHL.EQ.0) GOTO 1
      K1ZAHL = KZHV(1,N) + 1
      K2ZAHL = K1ZAHL + K3ZAHL - 1
      IF(ABS(H(N)).LT.1.E-15)  GOTO 1
      DO 20 K=K1ZAHL,K2ZAHL
20    F(K)=EPO(K)*H(N)
      IF(KZHX(0,N).GT.KZHX(1,N)) GOTO 41
      DO 40 M=1,IQM(N)
      KU=KZHX(M,N)
      DO 30 K=KU,K2ZAHL
30    F(K)=F(K)*S(MVK(K,M))
40    CONTINUE
41    DO 50 K=K1ZAHL,K2ZAHL
      WERTT(KVK(K)) = WERTT(KVK(K)) + F(K)
      IF(LUPAUS.LT.3) GOTO 50
      IF(ABS(F(K)).LT.1.E-15) GOTO 50
      WRITE(NOUT,100) KVK(K),
     ,NU,NN,N,K,K1ZAHL,K2ZAHL,WERTT(KVK(K)),EPO(K),F(K)
50    CONTINUE
100   FORMAT(' KVK,NU,NN,N,K,K1,K2,W,E,F',7I4,3E13.6)
    1 CONTINUE
      RETURN
      END
      SUBROUTINE ORDSRT(IIZ,KUNTEH,KOBEH)
      IMPLICIT REAL*8 (A-H,O-Z)
C     ORDSRT SORTIERT DEN GESAMTEN COMMONBLOCK LUP NACH AUFSTEIGENDER
C     ANZAHL VON SIGMAFAKTOREN
      INCLUDE 'par/QUAF_EFT'
C
      PARAMETER (NZAVMA=2*NZCMAX-1, NDIM4=NZPOMA*NZLWMA,
     *           NZLRH=(2*NZCMAX-3)*(NZCMAX-1),
     *   NZLREC=2*NZCMAX  + NZLRH+(NZLRH*(NZLRH+1))/2)
C
      COMMON /LUP/ KVK(NDIM1), JQ(NDIM1), INDPO(NDIM1),
     *    MVK(NDIM1,NZIQMA), EPO(NDIM1), WERTL(NDIM4,NDIM4),
     *    IZ,JZ, KZHV(2,NZLREC+1), LUPAUS, IQM(NZLREC+1),
     *    KZHX(0:NZIQMA,NZLREC+1)
C
C    KZHX(IQ,IIZ) GIBT DIE NIEDRIGSTE ELEMENT NUMMER AN MIT MINDESTENS
C                 IQ FAKTOREN IM RECORD IIZ
C
      KUNTH=KUNTEH
      KZAHL=KOBEH
      IQMH=IQM(IIZ)
      DO 10 IQ=0,IQMH
10    KZHX(IQ,IIZ)=0
C
      DO 100, IQ=0, IQMH
C        LOOP ANZAHL SIGMAFAKTOREN
C
         KZHX(IQ,IIZ)=KUNTH
         KUNTEN=KUNTH
         KOBH  =KZAHL
C
         DO 80, KH=KUNTEN, KZAHL
C
            IF (JQ(KH).EQ.IQ) GOTO 80
C           SIGMAFAKTOR FALSCH PLAZIERT
            KOBEN=KOBH
            DO 60, IH=KOBEN, KH+1, -1
               IF (JQ(IH).NE.IQ) GOTO 60
C              KANDIDAT ZUM AUSTAUSCH GEFUNDEN
               INT=JQ(IH)
               JQ(IH)=JQ(KH)
               JQ(KH)=INT
               INT=INDPO(IH)
               INDPO(IH)=INDPO(KH)
               INDPO(KH)=INT
               RE=EPO(IH)
               EPO(IH)=EPO(KH)
               EPO(KH)=RE
               DO 20, KQ=1, IQMH
                  IND=MVK(IH,KQ)
                  MVK(IH,KQ)=MVK(KH,KQ)
                  MVK(KH,KQ)=IND
20             CONTINUE
               KOBH=IH-1
               GOTO 70
C
60          CONTINUE
C           KEINEN TAUSCHKANDIDATEN MEHR GEFUNDEN, NAECHSTES IQ NEHMEN
            KUNTH=KH
            GOTO 90
C
70          CONTINUE
C           TAUSCHPARTNER GEFUNDEN UND GETAUSCHT, WEITERSUCHEN
C
80       CONTINUE
C
C        ENDE LOOP ANZAHL SIGMAFAKTOREN
90      IF(JQ(KZAHL).EQ.0) GOTO 110
100   CONTINUE
110   CONTINUE
      IF(LUPAUS.GT.1) WRITE(NOUT,999) (KZHX(IH,IIZ),IH=0,IQMH)
999   FORMAT(' KZHX ',20I4)
      RETURN
      END
